pull_request_rules:
  - name: automatic merge for Dependabot pull requests (LGTM success)
    conditions:
      - author=dependabot-preview[bot]
      - 'status-success=LGTM analysis: JavaScript'
      - status-success=continuous-integration/travis-ci/pr
      - status-success=codecov/patch
    actions:
      merge:
        method: squash
      delete_head_branch:
  - name: automatic merge for Dependabot pull requests (LGTM neutral)
    conditions:
      - author=dependabot-preview[bot]
      - 'status-neutral=LGTM analysis: JavaScript'
      - status-success=continuous-integration/travis-ci/pr
      - status-success=codecov/patch
    actions:
      merge:
        method: squash
      delete_head_branch:
