pull_request_rules:
  - name: automatic merge for Dependabot pull requests (LGTM success)
    conditions:
      - author=dependabot[bot]
      - 'status-success=LGTM analysis: JavaScript'
      - status-success=build (12.x)
      - status-success=build (14.x)
      - status-success=build (16.x)
      - status-success=build (18.x)
      - status-success=codecov/patch
    actions:
      merge:
        method: squash
      delete_head_branch:
  - name: automatic merge for Dependabot pull requests (LGTM neutral)
    conditions:
      - author=dependabot[bot]
      - 'status-neutral=LGTM analysis: JavaScript'
      - status-success=build (12.x)
      - status-success=build (14.x)
      - status-success=build (16.x)
      - status-success=build (18.x)
      - status-success=codecov/patch
    actions:
      merge:
        method: squash
      delete_head_branch:
