pull_request_rules:
  - name: automatic merge for Dependabot pull requests (LGTM success)
    conditions:
      - author=dependabot-preview[bot]
      - 'status-success=LGTM analysis: JavaScript'
      - status-success=Node.js CI / build (10.x) (pull_request)
      - status-success=Node.js CI / build (12.x) (pull_request)
      - status-success=Node.js CI / build (14.x) (pull_request)
      - status-success=Node.js CI / build (15.x) (pull_request)
      - status-success=codecov/patch
    actions:
      merge:
        method: squash
      delete_head_branch:
  - name: automatic merge for Dependabot pull requests (LGTM neutral)
    conditions:
      - author=dependabot-preview[bot]
      - 'status-neutral=LGTM analysis: JavaScript'
      - status-success=Node.js CI / build (10.x) (pull_request)
      - status-success=Node.js CI / build (12.x) (pull_request)
      - status-success=Node.js CI / build (14.x) (pull_request)
      - status-success=Node.js CI / build (15.x) (pull_request)
      - status-success=codecov/patch
    actions:
      merge:
        method: squash
      delete_head_branch:
