language: node_js
install:
  - yarn install
node_js:
  - lts/*
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn flow
  - yarn test src --coverage --collectCoverageFrom=src/** && yarn codecov -C
deploy:
  provider: npm
  email: cathsfz@gmail.com
  api_key:
    secure: nTiOrKgkhVdYrNXL+SE6WpF1neuQ0GNDiqsEZIsaFSSEtxpVeyYW5aOkJPaRosg4D03dd2dSsm9aIodTm98cY5elakvYquzwnRXrrrBUN3K0gV9R9MLPXnL6dOly10WcAk2NnZGB9+Bm0mhY7GvQ94554wKJpllw79ALwHDXVTKGd5PQtj3dDK1uh4qac0ZI+QdwjSwIqR6nv6Ty1axGt39FCx71eqcG3yKXlluWhkbiz0xlRMYBFAS3O0a6UAAMhnU5xJoQSVdwamJ69h+zRiQ25rVgvZdcaxUqrHJ5AyNo1bS58mqaw181yNeCLg55pYO2YtWQzbS1NmNLFroKn8ZG8zjWm5qnWef/MK6jYv9FguvJ9pJgDXOYhCPPNcb/kC80WdLFrSNyHgqHLlW3huDOt3duScdx032aYvTN8XKvyyFCDKvAd8B+aD8HOX9A6bgkMetHBo3X/D1ksbBOj2ZR+82iK6XKBLAD8EH2sEbZLFH1WipyvVd02lOqckijTQeoLuMBLDT3s4uMzRFtQP6FDjQ3WTRmADm7hakY0M+zjBFVDGNutnlvImbgVsIwklE4OdnYw0oLsiIt1aSUwrMQSWU2MCIQMqak1KyOZYLWUZ+2xVlc9F7y1FjE5NXrL1rQZ6UR07DcTe1pN1TMEv1ffrrtP/iXB98VCrPo6X0=
  on:
    repo: CatChen/versioned-storage
    branch: master
