name: JSR Package

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
      dry-run:
        type: boolean
        default: false
        required: false

jobs:
  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
        if: ${{ !inputs.dry-run }}
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/checkout@v5
        if: ${{ inputs.dry-run }}
        with:
          ref: ${{ github.ref_name || github.ref }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - run: |
          deno install
      - env:
          DRY_RUN: ${{ inputs.dry-run || false }}
        run: |
          if [[ "$DRY_RUN" = true ]]
          then
            deno publish --dry-run
          else
            deno publish
          fi
