# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# NPM publish uses OIDC (OpenID Connect) trusted publishing - no NPM_TOKEN required.
# Configure the trusted publisher at https://www.npmjs.com (Package → Settings → Trusted publishing).
# When using workflow_call from release.yml, set "Workflow filename" to release.yml on npmjs.com.
# Requires Node 22.14+ and npm 11.5.1+ (see https://docs.npmjs.com/trusted-publishers).

name: NPM Package

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
      dry-run:
        type: boolean
        default: false
        required: false

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC trusted publishing with npm
    steps:
      - uses: actions/checkout@v6
        if: ${{ !inputs.dry-run }}
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/checkout@v6
        if: ${{ inputs.dry-run }}
        with:
          ref: ${{ github.ref_name || github.ref }}
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          registry-url: https://registry.npmjs.org/
      - env:
          DRY_RUN: ${{ inputs.dry-run || false }}
        run: |
          yarn install
          yarn build
          npm config ls -l
          if [[ "$DRY_RUN" = true ]]
          then
            npm publish --dry-run
          else
            npm publish
          fi

  publish-github:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        if: ${{ !inputs.dry-run }}
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/checkout@v6
        if: ${{ inputs.dry-run }}
        with:
          ref: ${{ github.ref_name || github.ref }}
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          registry-url: https://npm.pkg.github.com
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: ${{ inputs.dry-run || false }}
        run: |
          yarn install
          yarn build
          yarn registry:github
          npm config ls -l
          if [[ "$DRY_RUN" = true ]]
          then
            npm publish --dry-run
          else
            npm publish
          fi
