name: Release

on:
  pull_request:
    branches: [master]
    types: [closed]
  workflow_run:
    branches: [master]
    workflows: ['Ship']
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'workflows/releases/') }}
    steps:
      - id: create-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          echo "::notice:: Branch name is $BRANCH_NAME"
          echo "::set-output name=branch-name::$BRANCH_NAME"

          HEAD_TAG=$(echo "$BRANCH_NAME" | cut -f3 -d "/")
          echo "::notice:: Head tag is $HEAD_TAG"
          echo "::set-output name=head-tag::$HEAD_TAG"

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            "/repos/$GITHUB_REPOSITORY/releases" \
            -f tag_name="$HEAD_TAG" \
            -f name="$HEAD_TAG" \
            -F generate_release_notes=true

  publish:
    needs: release
    if: ${{ needs.release.outputs.head-tag != '' }}
    uses: ./.github/workflows/npm-publish.yml
