name: Release

on:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/node.js.yml

  codeql:
    uses: ./.github/workflows/codeql-analysis.yml

  release:
    needs: [build, codeql]
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - uses: CatChen/node-package-release-action@v0.1
        with:
          release-type: patch

  publish:
    needs: release
    uses: ./.github/workflows/npm-publish.yml
    secrets: inherit
    with:
      tag: ${{ needs.release.outputs.head-tag }}
