name: Release

on:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      base_tag: ${{ steps.create-release.outputs.base_tag }}
      head_tag: ${{ steps.create-release.outputs.head_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          check-latest: true

      - id: create-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BASE_TAG=$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/$GITHUB_REPOSITORY/releases/latest" \
            -q .tag_name)
          echo "::notice:: Base tag is $BASE_TAG"
          echo "::set-output name=base-tag::$BASE_TAG"

          if test $(git diff --name-only $BASE_TAG | wc -l) != 0
          then
            git diff --name-only $BASE_TAG | xargs -n1 -I {} echo "::notice file={}::  File: {}"

            npm version patch
            HEAD_TAG=$(git describe --abbrev=0 --tags)
            echo "::notice:: Head tag is $HEAD_TAG"
            echo "::set-output name=head-tag::$HEAD_TAG"
            git push --follow-tags

            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              "/repos/$GITHUB_REPOSITORY/releases" \
              -f tag_name="$HEAD_TAG" \
              -f name="$HEAD_TAG" \
              -F generate_release_notes=true
          fi

  publish:
    needs: release
    if: ${{ needs.release.outputs.head_tag != '' }}
    uses: ./.github/workflows/npm-publish.yml
