name: Release

on:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
      prerelease:
        description: 'Prerelease'
        required: true
        default: false
        type: boolean
      skip-if-no-diff:
        description: 'Skip if no diff'
        required: true
        default: false
        type: boolean
      diff-targets:
        description: 'Diff Targets'
        required: false
        default: '{index.*,src/**/*,package.json,deno.json,tsconfig.json,README.md,LICENSE}'
        type: string
      dry-run:
        description: 'Dry run'
        required: true
        default: false
        type: boolean

jobs:
  node:
    uses: ./.github/workflows/node.yml
    secrets: inherit

  deno:
    uses: ./.github/workflows/deno.yml
    secrets: inherit

  codeql:
    uses: ./.github/workflows/codeql-analysis.yml

  release:
    name: Release
    needs: [node, deno, codeql]
    concurrency: release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.tag }}
      skipped: ${{ steps.release.outputs.skipped }}
    steps:
      - uses: actions/create-github-app-token@v2
        id: get-github-app-token
        with:
          app-id: ${{ secrets.CHECK_GIT_STATUS_BOT_APP_ID }}
          private-key: ${{ secrets.CHECK_GIT_STATUS_BOT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          token: ${{ steps.get-github-app-token.outputs.token }}

      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: yarn

      - run: |
          yarn install
          yarn husky # Set up pre-commit hook so npm version commit will copy the version to deno.json

      - id: release
        uses: CatChen/node-package-release-action@v2
        with:
          release-type: ${{ inputs.release-type || 'patch' }}
          prerelease: ${{ inputs.prerelease || false }}
          dry-run: ${{ inputs.dry-run || false }}
          skip-if-no-diff: ${{ inputs.skip-if-no-diff || github.event_name != 'workflow_dispatch' }}
          diff-targets: ${{ inputs.diff-targets || '{index.*,src/**/*,package.json,deno.json,tsconfig.json,README.md,LICENSE}' }}
          github-token: ${{ steps.get-github-app-token.outputs.token }}

  npm-publish:
    needs: release
    if: ${{ needs.release.outputs.skipped != 'true' }}
    uses: ./.github/workflows/npm-publish.yml
    secrets: inherit
    with:
      tag: ${{ needs.release.outputs.tag }}
      dry-run: ${{ inputs.dry-run || false }}

  jsr-publish:
    needs: [release]
    if: ${{ needs.release.outputs.skipped != 'true' }}
    uses: ./.github/workflows/jsr-publish.yml
    with:
      tag: ${{ needs.release.outputs.tag }}
      dry-run: ${{ inputs.dry-run || false }}
